#ifndef _DOLCESDK_PSP2_XML_XML_NODE_TYPES_H_
#define _DOLCESDK_PSP2_XML_XML_NODE_TYPES_H_

#if defined(__cplusplus)

namespace sce
{
namespace Xml
{
namespace Dom
{

// Node types info
#define SCE_XML_TOKEN_DOM_UNKNOWN				(-1)

#define SCE_XML_TOKEN_DOM_DOCUMENT				0x00
#define SCE_XML_TOKEN_DOM_ATTR					0x01
#define SCE_XML_TOKEN_DOM_ENTITY				0x02
#define SCE_XML_TOKEN_DOM_END_ELEMENT			0x03
#define SCE_XML_TOKEN_DOM_ELEMENT				0x04
#define SCE_XML_TOKEN_DOM_COMPACT_ELEMENT		0x05
#define SCE_XML_TOKEN_DOM_PRED_ELEMENT			0x06

#define SCE_XML_TOKEN_DOM_TEXT					0x08
#define SCE_XML_TOKEN_DOM_TEXT_BOOL				0x09
#define SCE_XML_TOKEN_DOM_TEXT_SHORT			0x0A
#define SCE_XML_TOKEN_DOM_TEXT_INT				0x0B
#define SCE_XML_TOKEN_DOM_TEXT_LONG				0x0C
#define SCE_XML_TOKEN_DOM_TEXT_FLOAT			0x0D
#define SCE_XML_TOKEN_DOM_TEXT_USER_DATA		0x0E
#define SCE_XML_TOKEN_DOM_TEXT_SKIPPED			0x0F

#define SCE_XML_TOKEN_DOM_SKIP_TEXT_CDATA		0x07
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_PI			0x17
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_DECL		0x17
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_COMMENT		0x1F
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_DTD			0x0F

#define SCE_XML_TOKEN_DOM_SKIP_TEXT_SIB_CDATA	0x27
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_SIB_PI		0x37
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_SIB_DECL	0x37
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_SIB_COMMENT 0x3F
#define SCE_XML_TOKEN_DOM_SKIP_TEXT_SIB_DTD		0x2F

#define SCE_XML_TOKEN_DOM_RW_ELEMENT			0x05

// Node info tokens
#define SCE_XML_TOKEN_DOM_HAS_CHILD					0x10	// 0001 0000
#define SCE_XML_TOKEN_DOM_HAS_SIBLING				0x20	// 0010 0000
#define SCE_XML_TOKEN_DOM_HAS_ATTR					0x40	// 0100 0000
#define SCE_XML_TOKEN_DOM_HAS_MODIFIED				0x80	// 1000 0000

#define SCE_XML_TOKEN_DOM_SIGN_BIT					0x10	// 0001 0000
#define SCE_XML_TOKEN_DOM_CONTINUE					0x20	// 0010 0000
#define SCE_XML_TOKEN_DOM_COMPRESSION				0x40	// 0100 0000

#define SCE_XML_TOKEN_DOM_HAS_MORE_ATTRS			0x10	// 0001 0000	// Attribute context
#define SCE_XML_TOKEN_DOM_HAS_TEXT_CHILD			0x28	// 0001 0000	// Text context
#define SCE_XML_TOKEN_DOM_HAS_TEXT_SIBLING			0x28	// 0001 0000	// Text context
#define SCE_XML_TOKEN_DOM_HAS_ENT_CHILD				0x10	// 0001 0000	// EntityTEXT context


#define SCE_XML_TOKEN_DOM_ELEMENT_ATTR_SIB_CHILD	0x74	// 0111 0100
#define SCE_XML_TOKEN_DOM_ROOT_DOCUMENT				0x10


#define SCE_XML_TOKEN_DOM_ELEMENT_NO_CHILD_SIB_ATTR	0x04	// 0000 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_CHILD				0x14	// 0001 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_SIB				0x24	// 0010 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_SIB_CHILD			0x34	// 0011 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_ATTR				0x44	// 0100 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_ATTR_CHILD		0x54	// 0101 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_ATTR_SIB			0x64	// 0110 0100
#define SCE_XML_TOKEN_DOM_ELEMENT_ATTR_SIB_CHILD	0x74	// 0111 0100
#define SCE_XML_TOKEN_DOM_RWELEMENT_ATTR			0x45	// 0100 0101
#define SCE_XML_TOKEN_DOM_RWELEMENT_ATTR_CHILD		0x55	// 0101 0101
#define SCE_XML_TOKEN_DOM_RWELEMENT_ATTR_SIB_CHILD	0x75	// 0111 0101
#define SCE_XML_TOKEN_DOM_RWELEMENT_ATTR_SIB		0x65	// 0110 0101
#define SCE_XML_TOKEN_DOM_ELEM_SIBL_CHILD			0x35
#define SCE_XML_TOKEN_DOM_ELEM_SIBL					0x25

#define SCE_XML_TOKEN_DOM_ENT_CHARREF				0x12
#define SCE_XML_TOKEN_DOM_ENT_UNKNOWN				0x42
#define SCE_XML_TOKEN_DOM_ENT_SIB					0x22


typedef enum NodeType
{
	nodeUnknown =			SCE_XML_TOKEN_DOM_UNKNOWN,
	nodeElement =			SCE_XML_TOKEN_DOM_ELEMENT,
	nodeElementRw =			SCE_XML_TOKEN_DOM_RW_ELEMENT,
	nodeAttribute =			SCE_XML_TOKEN_DOM_ATTR,
	nodeText =				SCE_XML_TOKEN_DOM_TEXT,
	nodeTexthasChild =		SCE_XML_TOKEN_DOM_HAS_TEXT_CHILD,
	nodeCdataSection =		SCE_XML_TOKEN_DOM_SKIP_TEXT_CDATA,
	nodeEntity =			SCE_XML_TOKEN_DOM_ENTITY,
	nodeProcessingInstruction = SCE_XML_TOKEN_DOM_SKIP_TEXT_PI,
	nodeComment =			SCE_XML_TOKEN_DOM_SKIP_TEXT_COMMENT,
	nodeDocument =			SCE_XML_TOKEN_DOM_DOCUMENT

} NodeType;


} // namespace Dom
} // namespace Xml
} // namespace sce

#endif // defined(__cplusplus)

#endif /* _DOLCESDK_PSP2_XML_XML_NODE_TYPES_H_ */

