/**
 * \usergroup{SceFios2}
 * \usage{psp2/fios2.h,SceFios2_stub}
 */

#ifndef _DOLCESDK_PSP2_FIOS2_PLATFORM_PSP2_H_
#define _DOLCESDK_PSP2_FIOS2_PLATFORM_PSP2_H_

#include <psp2/scebase.h>
#include <psp2/kernel/threadmgr.h>
#include <psp2/kernel/cpu.h>
#include <psp2/kernel/error.h>
#include <psp2/kernel/iofilemgr/stat.h>

#define SCE_FIOS_IO_THREAD_DEFAULT_STACKSIZE           (8*1024)
#define SCE_FIOS_DECOMPRESSOR_THREAD_DEFAULT_STACKSIZE (16*1024)
#define SCE_FIOS_CALLBACK_THREAD_DEFAULT_STACKSIZE     (8*1024)

#define SCE_FIOS_IO_THREAD_DEFAULT_PRIORITY           (SCE_KERNEL_HIGHEST_PRIORITY_USER+2)
#define SCE_FIOS_DECOMPRESSOR_THREAD_DEFAULT_PRIORITY (SCE_KERNEL_LOWEST_PRIORITY_USER-2)
#define SCE_FIOS_CALLBACK_THREAD_DEFAULT_PRIORITY     (SCE_KERNEL_HIGHEST_PRIORITY_USER+2)

#define SCE_FIOS_THREAD_DEFAULT_AFFINITY              SCE_KERNEL_CPU_MASK_USER_2
#define SCE_FIOS_IO_THREAD_DEFAULT_AFFINITY           SCE_FIOS_THREAD_DEFAULT_AFFINITY
#define SCE_FIOS_DECOMPRESSOR_THREAD_DEFAULT_AFFINITY SCE_KERNEL_THREAD_CPU_AFFINITY_MASK_DEFAULT
#define SCE_FIOS_CALLBACK_THREAD_DEFAULT_AFFINITY     SCE_FIOS_THREAD_DEFAULT_AFFINITY

#define SCE_FIOS_THREAD_FLAGS                         0

typedef SceUID SceFiosNativeFH;
typedef SceUID SceFiosNativeDH;
#define SCE_FIOS_NATIVEFH_INVALID SCE_UID_INVALID_UID
#define SCE_FIOS_NATIVEDH_INVALID SCE_UID_INVALID_UID
#define SCE_FIOS_READ_ALIGNMENT   512

#define SCE_FIOS_CST_MODE SCE_CST_MODE
#define SCE_FIOS_CST_SIZE SCE_CST_SIZE
#define SCE_FIOS_CST_CT   SCE_CST_CT
#define SCE_FIOS_CST_AT   SCE_CST_AT
#define SCE_FIOS_CST_MT   SCE_CST_MT
#define SCE_FIOS_CST_PRVT SCE_CST_PRVT

#endif
