#ifndef _DOLCESDK_H_
#define _DOLCESDK_H_

#pragma GCC warning "Including dolcesdk.h is deprecated. Please include individual headers."

#include <dolcesdk/utils.h>

#include <psp2/appmgr.h>
#include <psp2/apputil.h>
#include <psp2/arm.h>
#include <psp2/atrac.h>
#include <psp2/audiodec.h>
#include <psp2/audioenc.h>
#include <psp2/audioin.h>
#include <psp2/audioout.h>
#include <psp2/avconfig.h>
#include <psp2/avplayer.h>
#include <psp2/bgapputil.h>
#include <psp2/camera.h>
#include <psp2/codecengine.h>
#include <psp2/common_dialog.h>
#include <psp2/compat.h>
#include <psp2/ctrl.h>
#include <psp2/display.h>
#include <psp2/error.h>
#include <psp2/fiber.h>
#include <psp2/gxm.h>
#include <psp2/gxm/constants.h>
#include <psp2/gxm/errors.h>
#include <psp2/gxm/functypes.h>
#include <psp2/gxm/structs.h>
#include <psp2/gxt.h>
#include <psp2/hid.h>
#include <psp2/ime_dialog.h>
#include <psp2/incoming_dialog.h>
#include <psp2/io/devctl.h>
#include <psp2/io/dirent.h>
#include <psp2/io/fcntl.h>
#include <psp2/io/stat.h>
#include <psp2/jpeg.h>
#include <psp2/jpegarm.h>
#include <psp2/jpegenc.h>
#include <psp2/kernel/clib.h>
#include <psp2/kernel/constants.h>
#include <psp2/kernel/cpu.h>
#include <psp2/kernel/dmac.h>
#include <psp2/kernel/error.h>
#include <psp2/kernel/loadcore.h>
#include <psp2/kernel/modulemgr.h>
#include <psp2/kernel/openpsid.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/kernel/rng.h>
#include <psp2/kernel/sysmem.h>
#include <psp2/kernel/threadmgr.h>
#include <psp2/kernel/types.h>
#include <psp2/libdbg.h>
#include <psp2/libime.h>
#include <psp2/libssl.h>
#include <psp2/location.h>
#include <psp2/message_dialog.h>
#include <psp2/motion.h>
#include <psp2/mtpif.h>
#include <psp2/musicexport.h>
#include <psp2/net/http.h>
#include <psp2/net/net.h>
#include <psp2/net/net_syscalls.h>
#include <psp2/net/netctl.h>
#include <psp2/netcheck_dialog.h>
#include <psp2/notification_util.h>
#include <psp2/npdrm.h>
#include <psp2/npdrmpackage.h>
#include <psp2/paf.h>
#include <psp2/pgf.h>
#include <psp2/photoexport.h>
#include <psp2/power.h>
#include <psp2/promoterutil.h>
#include <psp2/pspnet_adhoc.h>
#include <psp2/pspnet_adhocctl.h>
#include <psp2/pss.h>
#include <psp2/pvf.h>
#include <psp2/registrymgr.h>
#include <psp2/rtc.h>
#include <psp2/sas.h>
#include <psp2/sblacmgr.h>
#include <psp2/scebase.h>
#include <psp2/screenshot.h>
#include <psp2/shellsvc.h>
#include <psp2/shutter_sound.h>
#include <psp2/sqlite.h>
#include <psp2/sysmodule.h>
#include <psp2/system_param.h>
#include <psp2/systemgesture.h>
#include <psp2/touch.h>
#include <psp2/trigger_util.h>
#include <psp2/types.h>
#include <psp2/udcd.h>
#include <psp2/usbd.h>
#include <psp2/usbserial.h>
#include <psp2/usbstorvstor.h>
#include <psp2/videodec.h>
#include <psp2/videoexport.h>
#include <psp2/vshbridge.h>

#endif
