/**
 * \usergroup{SceFios2}
 * \usage{psp2/fios2.h,SceFios2_stub}
 */


#ifndef _DOLCESDK_PSP2_FIOS2_PLATFORM_H_
#define _DOLCESDK_PSP2_FIOS2_PLATFORM_H_

#include <psp2/scebase.h>
#include <psp2/fios2/fios2_platform_common.h>
#include <psp2/fios2/psp2/fios2_platform_psp2.h>

#ifndef SCE_FIOS_NATIVE_DECOMPRESSOR_THREAD_DEFAULT_PRIORITY
#define SCE_FIOS_NATIVE_DECOMPRESSOR_THREAD_DEFAULT_PRIORITY SCE_FIOS_DECOMPRESSOR_THREAD_DEFAULT_PRIORITY
#define SCE_FIOS_NATIVE_PSARC_DEARCHIVER_TEMP_BUFFERS SCE_FIOS_PSARC_DEARCHIVER_TEMP_BUFFERS
#define SCE_FIOS_NATIVE_PSARC_DEARCHIVER_WORK_BUFFER SCE_FIOS_PSARC_DEARCHIVER_WORK_BUFFER
#define SCE_FIOS_NATIVE_PSARC_DEARCHIVER_WORK_BUFFER_SIZE SCE_FIOS_PSARC_DEARCHIVER_WORK_BUFFER_SIZE
#define SCE_FIOS_NATIVE_PSARC_DEARCHIVER_WORK_BUFFER_ALIGNMENT SCE_FIOS_PSARC_DEARCHIVER_WORK_BUFFER_ALIGNMENT
#endif

#endif
